# Generated by Django 5.1.2 on 2024-10-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingpayment',
            name='account_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
