# Generated by Django 5.1.2 on 2024-10-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='currency',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upcomingpayment',
            name='currency',
            field=models.CharField(default=1, max_length=6),
            preserve_default=False,
        ),
    ]
