# Generated by Django 5.1.2 on 2024-10-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0002_upcomingpayment_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingpayment',
            name='contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='upcoming_payments', to='commerzbank.contract'),
            preserve_default=False,
        ),
    ]
