# Generated by Django 5.1.2 on 2024-10-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0002_contract_currency_upcomingpayment_amount_and_more'),
        ('commerzbank', '0002_recipe_user'),
    ]

    operations = [
    ]
