# Generated by Django 5.1.2 on 2024-10-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0002_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contracts/'),
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
