# Generated by Django 5.1.2 on 2024-10-20 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0003_upcomingpayment_contract'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bank_account_number',
            new_name='account_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='reciver_address',
            new_name='receiver',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='reciver_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_address',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userlayer',
            name='layout',
            field=models.CharField(max_length=1000),
        ),
    ]
