# Generated by Django 5.1.2 on 2024-10-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0003_merge_20241019_2115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account_id',
            new_name='bank_account_number',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='transaction_name',
            new_name='reciver_address',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='from_account',
            new_name='reciver_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='title',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
