# Generated by Django 5.1.2 on 2024-10-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0004_rename_account_id_transaction_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bank_account_number',
            field=models.CharField(max_length=26),
        ),
    ]
