# Generated by Django 5.1.2 on 2024-10-20 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0004_rename_bank_account_number_transaction_account_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_id',
        ),
    ]
