# Generated by Django 5.1.2 on 2024-10-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0005_upcomingpayment_name_userlayer_access_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField()),
                ('transaction_name', models.CharField(max_length=250)),
                ('from_account', models.IntegerField()),
                ('to_account', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='userlayer',
            name='access_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userlayer',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userlayer',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
