# Generated by Django 5.1.2 on 2024-10-20 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0007_alter_upcomingpayment_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingpayment',
            options={},
        ),
        migrations.RemoveField(
            model_name='upcomingpayment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='upcomingpayment',
            name='time',
        ),
        migrations.AddField(
            model_name='contract',
            name='account_number',
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
