# Generated by Django 5.1.2 on 2024-10-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0008_alter_upcomingpayment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlayer',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='userlayer',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='userlayer',
            name='expires_in',
        ),
        migrations.RemoveField(
            model_name='userlayer',
            name='refresh_token',
        ),
    ]
