# Generated by Django 5.1.2 on 2024-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0011_loanoffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='nip',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(default=1, upload_to='recipes/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='store',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='recipeitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
