# Generated by Django 5.1.2 on 2024-10-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0012_alter_recipe_date_alter_recipe_nip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyalProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('points', models.IntegerField()),
            ],
        ),
    ]
