# Generated by Django 5.1.2 on 2024-10-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0013_loyalprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ai_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
