# Generated by Django 5.1.2 on 2024-10-19 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0014_recipe_ai_analyzed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ai_analyzed',
        ),
    ]
