# Generated by Django 5.1.2 on 2024-10-19 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerzbank', '0015_remove_recipe_ai_analyzed_qrcode'),
        ('commerzbank', '0016_remove_recipe_ai_analyzed'),
    ]

    operations = [
    ]
